config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments
  end

  root "posts#index"

  get '/about', to: 'pages#about'
  #Salirse de la session
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: {minimum: 5}
  validates :body,  presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :body))

    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to posts_path(@post)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(params[:post].permit(:title, :body, :photo))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <p class="comment_name"><strong><%= comment.name %></strong></p>
    <p class="comment_body"><%= comment.body %></p>
    <p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
  </div>

  <% if user_signed_in? %>
      <p><%= link_to 'Borrar', [comment.post, comment],
                     method: :delete,
                     class: "button",
                     data: { confirm: '¿Estas seguro?' } %></p>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
	<%= f.label :Nombre %><br>
	<%= f.text_field :name %><br>
	<br>
	<%= f.label :Comentario %><br>
	<%= f.text_area :body %><br>
	<br>
	<%= f.submit 'Agregar comentario'%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Batman Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    '/assets/application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag '/assets/application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div id="sidebar">
    <div id="logo">
      <%= link_to root_path do %>
          <%= image_tag "/assets/logo.jpg" %>
      <% end %>
    </div>

    <ul>
      <li class="category">Sitio Web</li>
      <li><%= link_to "Blog", root_path %></li>
      <li><%= link_to "Acerca de ", about_path %></li>
    </ul>

    <ul>
      <li class="category">Redes Sociales</li>
      <li><a href="http://instagram.com/luisguitrejo">Instagram</a></li>
      <li><a href="http://facebook.com/luisguitrejo">Facebook</a></li>
      <li><a href="https://github.com/luisguitrejo">Github</a></li>
    </ul>

    <% if !user_signed_in? %>
        <p class="sign_in"><%= link_to "Ingresar", new_user_session_path %></p>
    <% end %>
  </div>

  <div id="main_content">
    <div id="header">
      <% if current_page?(root_path) %>
          <p>Todos los posts</p>
      <% elsif current_page?(about_path) %>
          <p>Acerca de</p>
      <% else %>
          <%= link_to "Regresar a todos los posts", root_path %>
      <% end %>

      <% if user_signed_in? %>
          <div class="buttons">
            <button class="button"><%= link_to "Nuevo Post", new_post_path %></button>
            <a href="<%= destroy_user_session_path %>" data-method='delete' >Salir</a>
          </div>
      <% end %>
    </div>

    <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert") %>
    <% end %>

    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
	<div id="profile_image">
		<%= image_tag "/assets/foto.jpg" %>
	</div>

	<div id="content">
		<h1>Hola a todos</h1>
		<p>Bienvenidos a mi blog personal</p>
		<p>Aquí mostraré información de algunos sitios para viajar en Guanajuato México</p>
		<p>Si quieres saber de algunos de mis viajes puedes verlos en mi perfil de Instagram
      <a href="http://instagram.com/luisguitrejo">luisguitrejo</a> o checa mi perfil de Facebook
      <a href="http://facebook.com">luisguitrejo</a>, donde pongo algunas cosas nuevas.</p>
	</div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
			<ul>
				<% @post.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<%= f.label :Titulo %><br>
	<%= f.text_field :title %><br>
	<br>
	<%= f.label :Contenido %><br>
	<%= f.text_field :body %><br>
	<br>
    <%= f.label :Foto %><br>
    <%= f.file_field :photo %><br>
    <br>
	<%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
	<h1>Editar Post</h1>

	<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
	<div class="post_wrapper">
		<h2 class="title"><%= link_to post.title, post %></h2>
		<p class="date"><%= post.created_at.strftime("%B %d, %Y") %></p>
	</div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
	<h1>Nuevo Post</h1>

	<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
  <h1 class="title"><%= @post.title %></h1>
  <p class="date">
    Submitted <%= time_ago_in_words(@post.created_at) %> Ago
    <% if user_signed_in? %>
        | <%= link_to 'Editar', edit_post_path(@post) %> |
        <%= link_to 'Borrar', post_path(@post), method: :delete, data: { confirm: '¿Estas seguro?' } %>
    <% end %>
  </p>
  <p class="body"><%= @post.body %></p>
<div><%= image_tag(@post.photo, :style =>'width:200px') %></div>
  <div id="comments">
    <h2><%= @post.comments.count %> Comentarios</h2>
    <%= render @post.comments %>

    <h3>Agregar un comentario:</h3>
    <%= render "comments/form" %>
  </div>
</div>